title: "1. Anglerverein Schleusingen e.V."
description: "Angeln in Schleusingen, Thueringen"
url: "https://1av-schleusingen.de"
baseurl: "/av-schleusingen"
encoding: "utf-8"
lang: "de"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .context
